#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but 9th iteration adds "Hi"

n=10
while [ "$n" -gt 0 ];
do
    echo "Best School"
    if [ "$n" -eq 2 ];
    then
        echo "Hi"
    fi
    ((n--))
done