#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but 9th iteration adds "Hi"

n=0
while [ "$n" -lt 10 ];
do
    if [ "$n" -eq 3 ];
    then
        echo "bad luck"
    elif [ "$n" -eq 7 ];
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((n++))
done