#!/usr/bin/env bash
# This script is displaying the clock (12 hours 59 minutes)

h=0
m=1
while [ "$h" -lt 13 ];
do
    while [ "$m" -lt 60 ];
    do
        echo "$m"
        ((m++))
    done
    ((m = 1))
    ((h++))
    if [ "$h" -ne 13 ];
    then
        echo "Hour: $h"
    fi
done